### ISSUE TITLE
[Android] The "&nbsp" code wrongly appears in the list view when the note contains two or more spaces

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1000]
**[Affected Platforms]:**
- Samsung Galaxy S7 edge (Android 7.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v1938) installed.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Tap on the "New Note" button and trigger the keyboard.
3. Tap the "Space" key two times and go back to the list view.
4. Observe the note's preview.

**[Expected result]:**
- The "Take a note..." message is displayed in the note's preview.

**[Actual result]:**
- The "&nbsp" code is displayed in the note's preview.

**[Notes]:**
- The issue is also reproducible if there are three blank spaces between two characters.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/39307813-86c02454-496c-11e8-81e6-c97504ee1df8.gif)

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is still reproducible, but its behavior has changed.

Now, HTML code is disaplayed in the notes list when creating a note with at least 2 strings.
Also, HTML code is disaplayed in the notes list when adding a string before, between or after any other existing string when editing a note.

However, the notes are correctly displayed after synchronizing.

![20180427_143510](https://user-images.githubusercontent.com/37875464/39360788-48d14440-4a28-11e8-9d75-617eb6a2965e.gif)

**Comment by sebastienbarbier** [comment]
Will be fixed with PR #1009

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (notes-1_0-qa-v2003) installed. Verified on on Samsung S8 (Android 8.0.0) and Pixel (Android 8.0.0).
