### ISSUE TITLE
App crashes when trying to login

### ISSUE THREAD

**Issue by sivaraam** [mozilla/notes#1344]
### [Description]:
When I try to login to the Notes app it just crashes after I log-in to the browser and get back to the Notes app. When I re-open it, it asks me to login again. This happens regardless of whether I have the Notes plugin in firefox and whether I've started syncing in it.

### [Affected versions]:
1.0android-c2791 Android 5.1.1 on a Samsung Galaxy J1 ace

### [Prerequisites]:
You're not logged into the app.

### [Steps to reproduce]:
1. Install the app
1. Tap on Sign in.
1. Log into to Firefox accounts in the browser window that opens
1. Open the page seen after logging int with the Notes app.

### [Expected result]:
I'm logged in to the Notes app. Also possibly if I haven't started syncing in the browser yet, an informative message that advises me should be shown.

### [Actual result]:
App crashes.

### [Additional Notes]:
Initially I didn't have the Notes extension in my browser when I tried this. Then I tried to log in after installing the extension and syncing a few notes. The app crashes at that time too.

**Comment by SoftVision-CiprianMuresan** [comment]
Hi @sivaraam, thanks for the report. However "Notes" doesn't support Android 5 at this time. The issue is not reproducible on supported Android versions (6 and above).

We do have an informative message after you log in if you have no notes taken:
![screenshot_20180806-112211](https://user-images.githubusercontent.com/18304511/43705413-0d890bb0-996b-11e8-9f6a-8b05892b7496.png)

**Comment by sivaraam** [comment]
> Hi @sivaraam, thanks for the report. However "Notes" doesn't support Android 5 at this time.

Then why am I able to install it. I thought it was possible to specify a minimum required version which would prevent the app from being installed on unsupported devices.
