### ISSUE TITLE
Sync for Firefox Notes is not working

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1348]
Originally reported by @AngusEdward on the "Test Pilot" repo (issue [3787](https://github.com/mozilla/testpilot/issues/3787)).

> Bottom of notes window indicates that I need to log in to sync (although I already am), and when I log in it says it is connecting, then shows an error icon at the bottom of the notes window and essentially loops back saying that I need to log in. I have updated to the latest version of Firefox on the Mac (61.0.2 (64-bit)) and relaunched Firefox, to no avail.

Hi @AngusEdward, could you please post a copy of the "Browser Console" logs that are displayed during a login action. In order to do that open the "Browser Console" by pressing the "Cmd" + "Shift" + "J" keys ("Ctrl" + "Shift" + "J" on Windows) and copy the logs that are displayed after the login.

Also, it will be useful a copy after the "about:support" to make sure that other extensions are not in conflict with the "Notes" webextension.

And at last, can you please retest this issue using a new clean Firefox profile, maybe even safe mode, to eliminate custom settings as a possible cause (https://goo.gl/AR5o9d).

@vladikoff  , could you please look over this and give us your opinion.

**Comment by AngusEdward** [comment]
Here's the Browser Console contents after attempted login:


nsLoginManager: searchLogins: `formSubmitURL` or `httpRealm` is recommended nsLoginManager.js:445
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
https://mail.google.com/mail/u/0/#inbox : Unable to run script because scripts are blocked internally.
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
https://mail.google.com/mail/u/0/#inbox : Unable to run script because scripts are blocked internally.
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
https://mail.google.com/mail/u/0/#inbox : Unable to run script because scripts are blocked internally.
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] profile
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
https://mail.google.com/mail/u/0/#inbox : Unable to run script because scripts are blocked internally.
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
TypeError: (destructured parameter) is undefined background.js:131:1
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] news_updates.json
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] experiments.json
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
https://mail.google.com/mail/u/0/#inbox : Unable to run script because scripts are blocked internally.
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] profile
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
https://mail.google.com/mail/u/0/#inbox : Unable to run script because scripts are blocked internally.
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
https://mail.google.com/mail/u/0/#inbox : Unable to run script because scripts are blocked internally.
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=23. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=24. (Reason: CORS request did not succeed).
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
https://mail.google.com/mail/u/0/#inbox : Unable to run script because scripts are blocked internally.
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
https://mail.google.com/mail/u/0/#inbox : Unable to run script because scripts are blocked internally.
Empty string passed to getElementById(). m=sps,spl,spit,m_i,spt,t,it:437:240
https://mail.google.com/mail/u/0/#inbox/FMfcgxvxBXrxDXRKpBTHPrFRSRhZxVzj : Unable to run script because scripts are blocked internally.
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] authorization
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] oauth
OpenGL compositor Initialized Succesfully.
Version: 2.1 INTEL-10.36.19
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
FBO Texture Target: TEXTURE_2D
Error: Could not establish connection. Receiving end does not exist.
Browser.js:3:1937
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] authorization
TypeError: browser.messageManager is undefined[Learn More] webext-panels.js:67:5
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More]
oauth
Error: Could not establish connection. Receiving end does not exist.
Browser.js:3:1937
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] a3dbd8c5a6fd93e2
Error: Could not establish connection. Receiving end does not exist.
Browser.js:3:1937
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] sign
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] authorization
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] avatar
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] metrics
OpenGL compositor Initialized Succesfully.
Version: 2.1 INTEL-10.36.19
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
FBO Texture Target: TEXTURE_2D
[Show/hide message details.] Unknown localization message deleted lpfulllib.js:2
[Show/hide message details.] Unknown localization message accepted lpfulllib.js:2
[Show/hide message details.] Unknown localization message declined lpfulllib.js:2
[Show/hide message details.] Unknown localization message this_folder_s_items lpfulllib.js:2
[Show/hide message details.] Unknown localization message _nothing_to_copy lpfulllib.js:2
[Show/hide message details.] Unknown localization message _convert_to__legacy__shared__folder lpfulllib.js:2
[Show/hide message details.] Unknown localization message _pending_share lpfulllib.js:2
[Show/hide message details.] Unknown localization message _s_h_o_w lpfulllib.js:2
[Show/hide message details.] Unknown localization message _h_i_d_e lpfulllib.js:2
[Show/hide message details.] Unknown localization message _no_folder lpfulllib.js:2
[Show/hide message details.] Unknown localization message _add__item lpfulllib.js:2
[Show/hide message details.] Unknown localization message _add__form__fill lpfulllib.js:2
[Show/hide message details.] TypeError: chrome.tabs.getAllInWindow is not a function platformBackgroundOverride.js:1:5449
OpenGL compositor Initialized Succesfully.
Version: 2.1 INTEL-10.36.19
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
FBO Texture Target: TEXTURE_2D
[Show/hide message details.] Unknown localization message _open__my__vault lpfulllib.js:2
[Show/hide message details.] Unknown localization message _account__options lpfulllib.js:2
[Show/hide message details.] Unknown localization message _extension__preferences lpfulllib.js:2
[Show/hide message details.] Unknown localization message _download_extension_logs lpfulllib.js:2
Error: Could not establish connection. Receiving end does not exist.
Browser.js:3:1937
[Show/hide message details.] Unknown localization message _federated__login lpfulllib.js:2
[Show/hide message details.] Unknown localization message _to_continue__please_login_with__federated__login_ lpfulllib.js:2
[Show/hide message details.] Unknown localization message _something_went_wrong__please_try_again_ lpfulllib.js:2
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386
Cannot send function call result: other side closed connection (call data: ({path:"tabs.remove", args:[38]}))
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] authorization
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] oauth
OpenGL compositor Initialized Succesfully.
Version: 2.1 INTEL-10.36.19
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
FBO Texture Target: TEXTURE_2D
Error: Could not establish connection. Receiving end does not exist.
Browser.js:3:1937
TypeError: browser.messageManager is undefined[Learn More] webext-panels.js:67:5
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] authorization
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More]
oauth
Error: Could not establish connection. Receiving end does not exist.
Browser.js:3:1937
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] a3dbd8c5a6fd93e2
Error: Could not establish connection. Receiving end does not exist.
Browser.js:3:1937
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] sign
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] authorization
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] avatar
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] reauth
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] sign
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] key-data
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] keys
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] authorization
Ignoring response to aborted listener for 132210
Error: Message manager disconnected Browser.js:3:1937
[Show/hide message details.] Unchecked lastError value: Error: Invalid tab ID: 39 background.js:756
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] metrics
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] token
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] profile
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More] verify
OpenGL compositor Initialized Succesfully.
Version: 2.1 INTEL-10.36.19
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
FBO Texture Target: TEXTURE_2D
moz-extension://8b042e34-a411-8644-881b-a16cae961cab/background.html: chrome tabs query did not return a result while changing window focus

Log.js:3:3828
Unhandled promise rejection null
kinto-http.js:596:2166

**Comment by AngusEdward** [comment]
Here's the about:support text:


Name | Firefox
-- | --
61.0.2
20180807170231
Show Update History
release
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0
Darwin 17.7.0
Show in Finder                                /Users/Musefire/Library/Application Support/Firefox/Profiles/wqm8757w.default-1524855808347
about:plugins
about:buildconfig
about:memory
about:performance
about:serviceworkers
1/1 (Enabled by default)
5/4
Inactive
Found
Found
false
about:profiles

**Comment by AngusEdward** [comment]
Moving into Safe Mode didn't work, of course, because disabling extensions includes Test Pilot. :-)
