### ISSUE TITLE
Notes Not Loading On Certain Devices

### ISSUE THREAD

**Issue by GTHub23** [mozilla/notes#1368]
### [Description]:
I currently run Firefox Notes on 3 separate devices:

- Windows 7 desktop > Firefox 63 w/ Test Pilot v3.0.6vffecb95 and Firefox Notes 4.2.0
- Lenovo Tab3 8 Inch (TB3-850F) Tablet > Android Version 6.0 and Notes v1.1android-c2942
- Moto X Play (XT1562) Smartphone > Android Version 7.1.1 and Notes v1.1android-c2942

It is currently possible to view, edit, and sync notes on both my desktop and tablet. However, it is currently only possible ot sync notes to my phone, as the notes do not display correctly

### [Steps to reproduce]:
_Phone_
1. Open Notes
2. Tap Menu Button/Swipe for Menu
3. Sync Notes with Sync button
4. Select any note in list

_Tablet_
1. Open Notes
2. Tap Menu Button/Swipe for Menu
3. Sync Notes with Sync button
4. Select any note in list

_Desktop_
1. Open Notes via Toolbar button
2. Sync Notes with Sync button in sidebar
3. Select any note in list

### [Expected result]:
_Phone_
1. Loading spinner momentarily displays
2. Note text should be displayed

_Tablet_
1. Loading spinner momentarily displays
2. Note text should be displayed

_Desktop_
1. Note text should be displayed

### [Actual result]:
_Phone_
1. A seemingly blank note is displayed

_Tablet_
1. Note text is displayed after brief delay

_Desktop_
1. Note is displayed almost instantly

### [Additional Notes]:
_Phone_
1. While note appears blank, it is still possible to enter text into the note. However, this deletes all previously entered text and leaves only the newly entered text: for example,
     Type "Lorem Ipsum" into a note then click back
     Type "Lorem Ipsum 2" into the same note when it is displayed as blank
     "Lorem Ipsum 2" replaces "Lorem Ipsum" as the note text when synced
2. New notes can still be created and synced, but when attempting to edit a note after clicking back to the list of notes it again shows as blank

**Comment by EdgardoRios** [comment]
Hi,

I think I am facing a similar issue, or maybe it is the same. Notes are not being showed on my Galaxy Tab A. On the other hand, I can read, modify, and sync from Firefox in my computer with no issues.

Thanks.
Edgardo

**Comment by Uvik** [comment]
I have the exact same issue here. On my devices:
- Windows 10 laptop > Firefox 63.0, Firefox Notes 4.2.0: Notes show up as expected ✔️ 
- Essential PH-1 with Android 9.0 > Notes v1.1android-c2942: Notes are empty ❌ 

Thanks!

**Comment by GTHub23** [comment]
**Update**

Now I'm having the same issue on my tablet; notes can be seen in the list, but display as blank when opened. Desktop is currently the only way I can edit my notes

**Comment by Forger125** [comment]
I can confirm the issue on the Essential PH-1 (Android 9.0, Notes v1.1android-c2942): all notes are listed, and the first line of note content is displayed below the note title in the list view. However, when opening the note to view/edit, only the title is displayed (in the header bar) and no text is rendered/displayed in the text area. No issue with Firefox on Windows/Linux.

**Comment by Softvision-MariusComan** [comment]
I have also managed to reproduce the issue using the following steps:

**[Affected Platforms]:**
- Android 8.0.0 (Samsung S8) - Build Number R16NW.G950FXXU4CRI1
- Android 8.0.0 (Galaxy Note 8) - Build Number R16NW.N950FXXU5CRHA

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.3.0dev) custom built on 10/30/2018 installed.
- Have the latest version of the "Firefox Notes" application (app-release-signed) custom built on 10/30/2018 installed.
- You are logged into Notes with the same account on both instances.
- Have at least a note in the app.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and click the "Firefox Notes" toolbar button.
2. Open the Notes application and log in if needed.
3. Tap on any note and observe the behavior.

**[Expected result]:**
- The note is opened and the text is displayed correctly.

**[Actual result]:**
- The note is opened but is empty.

**[Notes]:**
- I have also tried to reproduce this issue on a Samsung S8 device that does not have the latest updates installed and I cannot manage to reproduce it.
- This issue is not reproducible on the following devices: Google Pixel (Android 8.0.0) Google Pixel (Android 9) and Huawei P8 Lite (Android 6.0).
- You can find the logs [here](https://drive.google.com/file/d/1aYyXxizjeEWYh4pVrWltBj6dnjxHH7Xp/view?usp=sharing).
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/47735304-f3d5eb00-dc74-11e8-996b-c88af47efb9d.gif)

**Comment by rdp5008** [comment]
Can confirm this on multiple devices.

Firefox notes on Firefox 63.0.1 on Linux installed and working fine.

I see same behavior where the body of the note does not appear on my mobile phones. I can see the title of each note in my list, but clicking on notes shows a blank page.

Devices:
Google Pixel (original) running Android 9
LG G7 ThinQ running Android 8.0.0

**Comment by vladikoff** [comment]
It seems like an issue with an update to the Android Webview, going to investigate and work on the fix, thanks for your patience !

**Comment by oldftg** [comment]
I just disabled chrome on my zenfone 5z which disabled chrome webview and enabled android system webview 68.0.3440.91
This fixed the issue of notes not displaying.

**Comment by Forger125** [comment]
I can confirm the solution mentioned by @oldftg resolves the issue on Essential PH-1: notes are displaying with Chrome disabled.

**Comment by EdgardoRios** [comment]
I had Chrome disabled on my Galaxy Tab A. I enabled it back and now notes are being displayed with Chrome enabled.

**Comment by oldftg** [comment]
An update pushed to system webview which broke notes again. Uninstalling the update fixed it but it appears that system webview has been updated with the same code that caused the problem with chrome webview.

**Comment by vladikoff** [comment]
The fix for Notes has landed and we will be pushing an update to Google Play soon!
