### ISSUE TITLE
Copy & Pasting a text with line break from notes to a plain text web page looses line break

### ISSUE THREAD

**Issue by scheinercc** [mozilla/notes#1383]
### [Affected versions]:
When copying a text with line break from Notes to a plain text area, the line break is lost.

### [Prerequisites]:
Firefox 64.0b9 (though I think it affects all versions)
Notes 4.2.0

### [Steps to reproduce]:
1. Create a new note. 
> this is text
> in two lines
> 
> and one paragraph

![image](https://user-images.githubusercontent.com/817856/48679707-aa2f4f00-ebe7-11e8-9801-4315c645a64f.png)

2. copy the note's content
3. Go to https://github.com/mozilla/notes/issues/new and paste it.

### [Expected result]:
> this is text
> in two lines
> 
> and one paragraph

### [Actual result]:
> this is textin two lines
> 
> and one paragraph

### [Additional Notes]:
1. You can also see the two lines merged into one without space between them in the note's title (see screenshot above) -> should be only the first line or both with a space between.
2. This could be related to issues  #534 and #1355

**Comment by kekkc** [comment]
Master bug should be https://github.com/mozilla/notes/issues/677

Guess since one year they should update Ckeditor to fix this. Main reason for Notes is to yeah document notes, which is broken since a year :P All advanced stuff like formatting, syncin, html works all great, but is useless if the basic is not working.

I'm using the very basic https://addons.mozilla.org/en-US/firefox/addon/textnotes/ until the core functionality is fixed here.
