### ISSUE TITLE
Can't sign in on desktop

### ISSUE THREAD

**Issue by joshdorsey** [mozilla/notes#1395]
### [Description]:
Signing in on desktop used to give me a "Reconnect to Sync" error, and would cause me to have to sign in again to see the same error again, and sometimes I get "Verify Your Account" but my account has been verified for a couple days now.  I've never successfully logged into notes on desktop.

### [Affected versions]:
4.2.0

### [Prerequisites]:
Android mobile device
Windows 10 desktop
Latest version of firefox on both devices
Latest version of notes on mobile

### [Steps to reproduce]:
1. Download android app, sign in
2. Enable extension in firefox, sign in

### [Expected result]:
Desktop browser is now signed in and will sync notes to mobile

### [Actual result]:
Mobile browser is signed in and appears to sync, but desktop browser gives the same pair of errors whenever you try to sign in.

### [Additional Notes]:
![image](https://user-images.githubusercontent.com/9029139/50080217-d5866900-01a8-11e9-9c67-0131c656f242.png)

This seems related to #1215, except they seem to have gotten it to work eventually?  Not sure.

**Comment by pwd-github** [comment]
Error message:
`{"code":400,"errno":109,"error":"Bad Request","message":"Invalid request parameter","info":"https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#errors","validation":"keys_jwk"}`

**Comment by vladikoff** [comment]
@pwd-github Hello, we are aware of the issue and deploying a server fix in the next few hours, sorry about that

**Comment by pwd-github** [comment]
@vladikoff awesome, no worries and thank you.

**Comment by thestandardtoaster** [comment]
as far as I can tell this still does the exact same thing, I've tried removing and re-adding the add-on multiple times, signing in multiple times not sure what more I can do

**Comment by SavedEmperor** [comment]
was this fixed? because i have the same problem

**Comment by engineervix** [comment]
I am also having the same problem, any fix? I'm using Firefox 65.0.1 (64-bit) on Ubuntu 18.04 and Firefox Notes v4.3.3

**Comment by jaccarmac** [comment]
This is happening for me now. Android app is able to reauth, but the desktop addon (which hasn't had auth issues before) is not.

**Comment by Ilphrin** [comment]
Same problem here, Android app is working for connection and sync, but not desktop

**Comment by vladikoff** [comment]
Nightly might have problems with this in https://github.com/mozilla/fxa/issues/2411

Not Firefox 65 though ...

**Comment by abu1** [comment]
Helllllllllllo from 2020...

Been having this problem for a _while_, anything yet? I am using Waterfox, 2020.05 (64-bit), latest version to date, but been having this problem since a couple of versions back. 

Here is all the data I get on the error:
Json:
`{
  "code": 400,
  "errno": 109,
  "error": "Bad Request",
  "message": "Invalid request parameter",
  "info": "https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#errors",
  "validation": {
    "keys": [
      "keys_jwk"
    ]
  }
}`
![image](https://user-images.githubusercontent.com/8573307/82125600-da639980-975b-11ea-99f1-ac7d646c7e76.png)
and in Raw data:
`{
  "code": 400,
  "errno": 109,
  "error": "Bad Request",
  "message": "Invalid request parameter",
  "info": "https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#errors",
  "validation": {
    "keys": [
      "keys_jwk"
    ]
  }
}`
![image](https://user-images.githubusercontent.com/8573307/82125613-ef402d00-975b-11ea-8805-0f8519dbd730.png)
and in Headers:
`Connection: keep-alive
Content-Length: 203
Content-Security-Policy: default-src 'none' ; script-src resource:; 
Content-Type: application/json; charset=utf-8
Date: Sat, 16 May 2020 16:51:13 GMT
Timestamp: 1589647873
access-control-allow-origin: *
access-control-expose-headers: WWW-Authenticate,Server-Authorization,Timestamp,Accept-Language
cache-control: no-cache
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: DENY
x-xss-protection: 1; mode=block

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Host: oauth.accounts.firefox.com
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0 Waterfox/56.3
`
![image](https://user-images.githubusercontent.com/8573307/82125624-f9fac200-975b-11ea-8478-0bfcfb6b2443.png)

Hope this helps get solved soon

**Comment by vladikoff** [comment]
>  I am using Waterfox, 2020.05 (64-bit)

Hm is Waterfox Firefox 56?

**Comment by abu1** [comment]
I believe so. It's what Firefox looked like before it got "quantumed". I downgraded because of Add-ons, one of them was notes

**Comment by abu1** [comment]
Any progress or additional information you require?

**Comment by abu1** [comment]
So, an update to the problem. I intealled the newest version of Waterfox (which is starting to look like quantum) and now get the login window porperly. Hooray! However, I can't login because of this error. Can anyone help?

![image](https://user-images.githubusercontent.com/8573307/83803303-30dc3d80-a661-11ea-8ae6-1b299b7360ca.png)

**Comment by vladikoff** [comment]
The error you got has a bug filed in https://github.com/mozilla/fxa/issues/4005 

If possible could you check the `Network` panel in DevTools and see if there are any requests highlighted red?

**Comment by abu1** [comment]
Where is "Devtools"?

**Comment by vladikoff** [comment]
@abu1 https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor#:~:text=There%20are%20a%20few%20different,on%20OS%20X%20and%20Linux).

**Comment by abu1** [comment]
Okay, here is what I got

![image](https://user-images.githubusercontent.com/8573307/83806268-1c4e7400-a666-11ea-9b9a-0a127b6a9082.png)

**Comment by vladikoff** [comment]
@abu1 Are you able to open this file in your browser:

https://accounts-static.cdn.mozilla.net/bundle-7127cb70c2c35809c0b78da9e96ecafeb6819dbe/vendors~fxaCryptoDeriver.bundle.js

and/or this one:

https://accounts-static.cdn.mozilla.net/bundle-7127cb70c2c35809c0b78da9e96ecafeb6819dbe/head.bundle.js

**Comment by abu1** [comment]
The other problem, for Waterfox Classic, still exists. 

However, for Waterfox (Current?) it worked. Got it! Turns out a program was blocking my access to those websites. Works now! Thanks!
