### ISSUE TITLE
Addon gets fooled by fingerprint protection timezone.

### ISSUE THREAD

**Issue by Rustlang4Future** [mozilla/notes#1507]
### [Description]:
I have enabled resistfingerprint pref enabled in about:config page of FF.
when i open notes sidebar, the time it shows is for 0 timezone rather than my own.
there isn't much problem if this issue be only this but i afraid it also affect notes syncing and cause issue to new/old note recognizing. (with Notes app on mobile devices that use our real local timezone.)

I only opened this issue to ask please consider this.

May be also some other issues are caused by this (#1484 , #1476 , or may be even #1369 )

### [Affected versions]:
Addon version: 4.3.5
Android version: 1.3android-c3202 (Version Code: 1048585)

**Comment by Podesta** [comment]
I don't have this issue. The notes show on both devices for me, irrespective of when I create them. Whenever I edit/create/delete a note, it forces a sync on the device that performed the action. It doesn't necessarily triggers a sync on the other devices, it depends on when you last synced. Once the other syncs, either naturally or by me clinking the sync button, all the notes are properly updated.

I don't believe it has anything to do with the different timezone, it is just something that Firefox does, it doesn't sync every 30 seconds. There were a few complaints awhile back that the send tabs to devices used to "eat" a few tabs. The problem is that if both devices didn't sync at a reasonable time window, it would indeed disappear. Again, I doubt the issues you are facing are related to different timezones.

**Comment by 3j9fkyahunqoxwqu** [comment]
Hello
Thank you for your comment.

Seems that i explained the issue badly.
There isn't any issue untill now but because firefox does saves history of every note, i opened this issue so because few people uses resistfingerprinting pref, it also considered in the service that in the future it won't cause problems. 

The firefox note addon show notes correctly but the time it shows last sync is for 0 timezone because browser send that timezone to all websites and addons to mask all data as Tor browser.

There isn't problem because it is the nature of resistfingerprinting. 

But i only said it to won't get forgotten when developing service. 

The service is really good till now thanks to great work of mozilla people.
