### ISSUE TITLE
No sync button

### ISSUE THREAD

**Issue by itadmfcl** [mozilla/notes#1526]
### [Description]:
After installing Notes on latest firefox for Windows and for Mac, neither show any ability to sync and notes are not synced. 

FF is logged into FF account and all other syncing works. Local Storage test passes.

### [Affected versions]:
Latest Release (83.0). Both Win and Mac affected.

### [Steps to reproduce]:
Install extension

### [Expected result]:
Syncing button appears bottom.

### [Actual result]:

No syncing 
![image](https://user-images.githubusercontent.com/75317842/100749055-23a2d000-33b2-11eb-978a-c05110fda3af.png)

**Comment by Hummeri** [comment]
Hi! I am not a Firefox note developer myself, but I was subscribed to this github project and simply forgot to unsubscribe.
Firefox notes discontinued by Mozilla,
As shown as here. https://blog.mozilla.org/blog/2020/09/17/update-on-firefox-send-and-firefox-notes/
However if you want a syncing platform that is reliable (and not Google/other cloud company related) I may suggest you to use 
Syncthing, and sync basic txt files around all devices you use (gnu/linux, Windows,Mac,Android, no support for ios yet). I been using Syncthing since Mozilla announced they would discontinue Firefox notes, and Syncthing was surprisingly more reliable and syncing was more real-time than Firefox notes.
Hope this helps!

**Comment by itadmfcl** [comment]
Ahh, I guess I missed the announcement. That's sad. Thanks for letting me know though. 

Syncthing is great, however was kind of hoping for something that would work in the browser across devices. There is Google Notes, but would prefer opensource or more diverse options than Google.
