### ISSUE TITLE
Google access notification on install

### ISSUE THREAD

**Issue by autonome** [mozilla/notes#175]
This just feels all wrong. Why does a notes add-on need to send my info to Google? Why am I forced to make a choice between sending data to Google or not being able to use the add-on?

https://i.imgur.com/smD6vvX.png

(Also, hitting cancel leaves Test Pilot stuck at "Enabling".)

**Comment by vladikoff** [comment]
@autonome If you enable "Do-Not-Track" no info will be sent.

**Comment by johngruen** [comment]
@autonome hey, so Test Pilot is opt-in. We do collect data in order to understand how people are using the experiments so we can reason about how to develop them. Every experiment has a short notice that describes the data on the experiment page as well as a full rundown of the exact pings we send in: https://github.com/mozilla/notes/blob/master/docs/metrics.md

@vladikoff is right to point out that setting DNT will disable all communication with GA. I'm going to file a in issue on Test Pilot to better handle the don't-install hang you're seeing

**Comment by johngruen** [comment]
Since there's nothing actionable here, i'm going to go ahead and close.
