### ISSUE TITLE
Sidebar not showing Notes

### ISSUE THREAD

**Issue by Haroldgomez777** [mozilla/notes#192]

**Comment by mnowaksuse** [comment]
I don't see 'Notes' in 'Show Sidebars' menu on two instances Firefox ESR 52.2.0 on openSUSE Leap 42.3. Firefox Notes version is 1.6.3dev.

**Comment by Natim** [comment]
Sidebar supports arrived in Firefox 56, so any prior version of Firefox will not work.

**Comment by SoftVision-EmilPasca** [comment]
This issue was also mentioned on https://github.com/mozilla/testpilot/issues/2731 where I've suggested that the "Enable Notes" button should not be displayed for the users that tries to install the experiment form an outdated version and also a notification should be displayed on the experiment details page when this occurs.

**Comment by johngruen** [comment]
We need to add a minimim version notice to the Test Pilot, add-on has a min-version flag as well. We believe that 52 does not know about the min-version prop.

**Comment by vladikoff** [comment]
https://github.com/mozilla/notes/blob/master/src/manifest.json#L10

**Comment by Haroldgomez777** [comment]
ok
