### ISSUE TITLE
Add a saving status indicator

### ISSUE THREAD

**Issue by Natim** [mozilla/notes#208]
Tell people that their notes were saved.

**Comment by Siddhinita** [comment]
@Natim I propose adding a snackbar to alert the user. What do you think?

**Comment by vladikoff** [comment]
@Siddhinita we have a design almost ready

**Comment by Siddhinita** [comment]
@Natim Is it already implemented?If not, can I work on it?

**Comment by ryanfeeley** [comment]
Will we have a time stamp? If yes, will it look different than, for example:

* Thursday 3:45 PM

(my locale)

**Comment by Natim** [comment]
@ryanfeeley we can have a timestamp if you'd like to

**Comment by Natim** [comment]
@Siddhinita When you think about a snackbar are you thinking of something like that?

![snackbar](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B6Okdz75tqQsZV9TS3lTVHFzRUE/components_snackbar_usage_fabdo_005.webm)

**Comment by Siddhinita** [comment]
@Natim..Yes.

**Comment by ryanfeeley** [comment]
How is this? Text colour is #808080
![saving-indicator](https://user-images.githubusercontent.com/68213/29462458-6dac57a6-83fd-11e7-8e17-dfec28af3b28.gif)

**Comment by Natim** [comment]
I kind of like it, how will it work with the syncing then?

**Comment by ryanfeeley** [comment]
@Natim [It would work the same.](https://mozilla.invisionapp.com/share/6VBUYHMRB#/235284916_Desktop_Sidebar) The save status indicator becomes the sync status indicator. The sync icon moves to the left and is replaced with a ⋯ button that lets user disable syncing.

**Comment by ryanfeeley** [comment]
If we have access to a time stamp,  use locale's equivalent of: 
    Saved Thursday 3:45 PM

**Comment by johngruen** [comment]
Todo: me
https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#experiments

**Comment by vladikoff** [comment]
@cedricium Hey! do you have time to add the menu functionality for this?

![](http://v14d.com/i/59c1209ae82ca.jpg)

Following this design but the menu will have multiple items. One of them is "Feedback".

**Comment by cedricium** [comment]
@vladikoff yea, I'll get started right away! Besides "Feedback", what would be the other menu items?

**Comment by Natim** [comment]
From top to bottom:

- Feedback
- Disable Sync

**Comment by vladikoff** [comment]
@Natim also do we want to make the status "Editing" / "Saved" indicator part of this?

**Comment by vladikoff** [comment]
@cedricium not sure if I mentioned earlier but using a pre-built component can save time with the `menu`: https://getmdl.io/components/#menus-section

**Comment by Natim** [comment]
Up to @cedricium

**Comment by vladikoff** [comment]
@cedricium see https://github.com/mozilla/notes/issues/208#issuecomment-323364292

**Comment by cedricium** [comment]
In terms of styling, how should the menu icon when hovered look like? Above, the hovered state has some padding of white around it. This was designed similarly to this:
![screen shot 2017-09-19 at 11 26 16 am](https://user-images.githubusercontent.com/16343560/30608549-a1ae8120-9d2d-11e7-8e82-456b21c96bf9.png)

However, the hovered state for the footer buttons take up the entire space of the element, like so:
![screen shot 2017-09-19 at 11 26 28 am](https://user-images.githubusercontent.com/16343560/30608588-c027f87a-9d2d-11e7-9195-cc20c3622a5d.png)

So my question is, would the following hovered styling be okay since it follows the nature of the button to it's left?:
![screen shot 2017-09-19 at 11 24 06 am](https://user-images.githubusercontent.com/16343560/30608651-e30122b8-9d2d-11e7-985d-af7288c0d48c.png)

Hopefully that makes sense haha.

**Comment by ryanfeeley** [comment]
@cedricium Great question! Ideally I want it to match desktop menus as much as possible. Let me find the spec but this is the gist of it. 
![hover](https://user-images.githubusercontent.com/68213/30612573-0e75c0dc-9d53-11e7-8303-b383475b2f5b.gif)

**Comment by cedricium** [comment]
@ryanfeeley matching the desktop makes sense and IMO looks really clean. Thanks for looking for that spec.

@Natim @vladikoff did you want me to handle the 'Disable Sync' listener? I'm a little confused however because when I press the 'Sync Your Notes' button, I still get the 'Syncing isn't ready...' message. But it looks like QA has been working with actually syncing...?

**Comment by ryanfeeley** [comment]
@cedricium Are you ready for this? Full spec! Did think I could share this publicly. https://mozilla.invisionapp.com/share/PYC5LJJXG#/229940647_Toolbars

**Comment by ryanfeeley** [comment]
@cedricium Also https://mozilla.invisionapp.com/share/H3BIW4C9U#/screens/230516723_Application_Menu

**Comment by Natim** [comment]
> It looks like QA has been working with actually syncing...?

Yes you are right were are basing the sync work on top of the sync-v4 branch.
