### ISSUE TITLE
Add support for autolink (typing and pasting)

### ISSUE THREAD

**Issue by Natim** [mozilla/notes#233]
Refs https://github.com/quilljs/quill/issues/109#issuecomment-219265086

**Comment by cedricium** [comment]
As far as typing goes, I used the code [outlined in this answer](https://github.com/quilljs/quill/issues/109#issuecomment-278181150) and it works pretty well. Based on the regex used in that code, only text beginning with `http://` or `https://` will be recognized, whereas Google Docs matches text beginning with just `www.` as well.

Another note with the example code given in the above comment is that the typed text should be followed by whitespace (either a space or newline will do), otherwise any proceeding text may become a part of the link itself. One way of preventing this would be to implement the <kbd>Cmd/Ctrl</kbd><kbd>K</kbd> shortcut to allow toggling on and off linking for highlighted text.

**Comment by vladikoff** [comment]
> only text beginning with http:// or https:// will be recognized

That sounds good for starters 👍 

> Another note with the example code given in the above comment is that the typed text should be followed by whitespace (either a space or newline will do)

That's also fine. I think G Docs might do this too.

> Do you suggest removing that editing tooltip entirely, or replacing it with our own?  

If we can avoid the tooltip entirely that would be great. Due to the sidebar nature of the project we are trying to stay away from these tooltips :)

**Comment by cedricium** [comment]
Created a pull request with the basic support for links. Still need to add link mouse click events to the analytics.

**Comment by Natim** [comment]
Fixed with 75c751452146e488b39e7b8c86fb38df4bdc3ecb
