### ISSUE TITLE
In a formatted text, an inserted or written link doesn't keep active the preexistent formatting

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#271]
[Affected versions]:
- Firefox 56 and up
- Firefox Notes v1.8.0rc3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (1.8.0rc3).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Have some styled text (Font size, Bold/Italic/Strikethrough style etc.).
3. Type or insert a link in the formatted text.
4. Observe the behavior.

[Expected result]:
- The link is correctly displayed, respecting the preexistent formatting text style.

[Actual result]:
- The link is not correctly displayed and it doesn't respect the preexistent formatting text style.

[Notes]:
- Here is a screen recording of the issue:
![notes - writing issue](https://user-images.githubusercontent.com/31244235/31077219-64b0630c-a786-11e7-8ff3-d031dbafd486.gif)

**Comment by Softvision-CristinaBadescu** [comment]
I was able to reproduce this issue in two different scenarios, using Firefox Notes 1.8.0dev version, on latest Nightly 58.0a1 build (2017-10-19), on Windows 10x64, Mac 10.12 and Ubuntu 14.04.

**First scenario:**

[Steps to reproduce]
1. Write something in "Notes" sidebar, without formatting.
2. Change the font size and select any formatting options.
3. Type a link and observe its behavior.

[Actual results]
- The typed link is not keeping the active text formatting.

Here is a screen recording with this behavior:
![notes - scenario 1](https://user-images.githubusercontent.com/31244235/31823781-daa44bea-b5b5-11e7-97ed-a8e5aa3ba2cf.gif)


**Second scenario:**

[Steps to reproduce]
1. Write something in "Notes" sidebar, without formatting.
2. Change the font size, select any formatting options and paste a link.
3. Start writing something and observe the behavior.

[Actual results]
- The pasted link is not keeping the active text formatting when starting writing something.

Here is a screen recording with this behavior:
![notes - scenario 2](https://user-images.githubusercontent.com/31244235/31823788-e40d3c3c-b5b5-11e7-8011-6c0baabeb585.gif)

**Comment by Natim** [comment]
Did you try it with latest master?

**Comment by Natim** [comment]
We don't have a build with that feature landed yet

**Comment by Softvision-CristinaBadescu** [comment]
The build I've used was created in the morning (about 8 hours ago) by cloning the master branch from Notes repository.

**Comment by Natim** [comment]
Ok then thanks :)

**Comment by cedricium** [comment]
I see the issue now - it deals with the way Quill creates the elements when applying formatting.

If you have active formatting, for example `bold` and `italics` and some text that says 'hello world', then the HTML of the Notes editor would like this:
```html
<div>
  <strong>
    <em>
      hello world  I <- user's cursor
    </em>
  </strong>
</div>
```
Then if a URL is typed following the 'hello world' (where the cursor is in the above code), the moment our link-detection function applies the `link` format an `<a>` tag is created and that gets placed outside of the `<strong>` and `<em>` elements, resulting in something like this assuming 'https://github.com/mozilla/notes' was typed:

```html
<div>
  <strong>
    <em>
      hello world
    </em>
  </strong>
  <a href="https://github.com/mozilla/notes">https://github.com/mozilla/notes</a>
</div>
```

What you'd expect to be:
**_hello world https://github.com/mozilla/notes_**
turns out instead like:
**_hello world_** https://github.com/mozilla/notes

Now if a link was already typed **then** formatting options were applied, those formatting options would not get dumped because the `<strong>`, `<em>`, and `<s>` (strike-through) tags are built around the `<a>` tags.

I'm thinking this is a Quill bug but because they don't have native support for auto-detecting links (either typed or pasted), I'm not sure what progress will get made to correct this. @Natim let me know if you think I should file a bug with them. I'll need to think about a way to fix this in the mean time.

cc: @vladikoff

**Comment by Natim** [comment]
@cedricium Yes I guess it worth filing a bug for it.
