### ISSUE TITLE
Erasing the text after disabling FxA doesn't bring back the Sync data if re-enabling the FxA

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#502]
[Affected versions]:
- Firefox 57.0.1 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with "Firefox Notes" v2.0.0rc2 installed.
- Log into the FxA.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Type some text into the sidebar.
3. Click the 3 dot menu button and select "Disable Sync" option.
4. Press "Ctrl"+"A" keys, then "Delete" key.
5. Click on the "Sync Your Notes" button and log into the previous FxA.
6. Observe the Sidebar's content.

[Expected result]:
- The text typed at step 2 is displayed.

[Actual result]:
- The Sidebar's content is empty, no text is displayed.

[Additional Notes]:
- This issue doesn't reproduce when the second FxA login takes place on another device.
- Here is a screencast of the issue:

![erase re enable](https://user-images.githubusercontent.com/26000308/33723919-9c6fc73c-db76-11e7-8710-f222be722034.gif)

**Comment by vladikoff** [comment]
@Natim any idea about this one?

**Comment by Natim** [comment]
It is not a bug it is because nothing changed remotely so it synced the local modification

**Comment by SoftVision-PaulOiegas** [comment]
@vladikoff @Natim Hmmm, I can understand it from a point of view, but this could also cause loss of data in some cases. If you delete the data by mistake or someone accesses your PC and even if you are disconnected from FxA, it clears your saved notes. If you relog, you will permanently loose them. So, you are either forced to log on a different device to bring back your notes, either to reinstall Notes (just checked and it works).

Also, we have a bit of inconsistency here. 
- 1st scenario: 
If you use 2 FxA accounts, you disconnect from 1st account, you clear the data from it and you relog with the 2nd account. The content from 2-nd account is brought to Notes when sync occurs. And if you disconnect again from 2-nd, clear everything and reconnect on 1st, the notes from first are brought without any issue back.

- 2nd scenario:
One FxA account used, you disconnect, clear everything and after you uninstall Notes. If you reinstall it back and log with the same account, the content is correctly brought back.

I think in Carmen's scenario it should work the same as both the above scenarios. I'm concerned that otherwise probably the users won't know that this will happen and what it's the workaround and we'll have reports of data loss.

**Comment by Natim** [comment]
I guess I understand your point, when disconnecting and reconnecting, you would like to see a merge conflict as if you never connected to this server, while currently we just sync as if you were never disconnected.

I guess the misunderstanding is that you don't remove the note, you edit the content of the note offline to an empty one.

How does it work if you take again your scenarios and instead of empty use the new note content?

**Comment by SoftVision-PaulOiegas** [comment]
I'm not sure that I really understand your question. You want to know what happens in the 2 scenarios mentioned at inconsistency if you edit instead of clear? Or you want to know what happens on Carmen's scenario if you edit the note and not clear it before reconnect?

**Comment by Natim** [comment]
Yes I want to know what is the expected behavior when you think of editing the content rather than removing it. Because we don't have such concept as clear the note so far.

**Comment by SoftVision-PaulOiegas** [comment]
I will have to test this tomorrow since is kind of late for us already and my team already left.

**Comment by Softvision-MariusComan** [comment]
I have not managed to test the above scenarios because this issue is blocked by https://github.com/mozilla/notes/issues/503.

**Comment by Softvision-MariusComan** [comment]
The issue is no longer reproducible on the latest version of Firefox Notes (2.0.0rc4) on the latest Firefox release and Nightly. Thanks for the effort to fix this issue. 👍
