### ISSUE TITLE
A word is wrongly marked as misspelled, if the caret is placed inside of it and a formatting style is applied

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#521]
**[Notes]:**
- It seems that the word is divided by the text caret in two separate words after the formatting style option is applied and the "SpellChecker" verify both words if they are grammatically correct.

**[Affected versions]:**
- Firefox 57.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.2.0dev custom build from 12.19.2017) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Write a grammatically correct word in the "Firefox Notes" sidebar (e.g. enhancement).
3. Place the text caret anywhere inside the word.
4. Click the "Bold" button and observe the behavior.

**[Expected result]:**
- Nothing happens.

**[Actual result]:**
- The word or a part of it, is marked as grammatically incorrect by the "SpellChecker".

**[Additional Notes]:**
- The issue is reproducible with the TxP version of "Firefox Notes".
- The issue is also reproducible if you choose the "Italic" or the "Strikethrough" format style.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/34157312-c220dcb2-e4c9-11e7-93f7-af92c1c89d0c.gif)

**Comment by vladikoff** [comment]
cc @mgsy this is an interesting one. We can repro this on https://ckeditor5.github.io/ as well

**Comment by Mgsy** [comment]
AFAIR this is a known issue, but right now I can't find a proper ticket. @Reinmar, could you say something more about this one?

**Comment by vladikoff** [comment]
Need to revisit this in CKEditor..., @Mgsy wanna check the stable version now?

**Comment by Mgsy** [comment]
>Need to revisit this in CKEditor..., @Mgsy wanna check the stable version now?

I've checked it and this issue is still reproducible on the latest master.

**Comment by Reinmar** [comment]
This is not going to be fixed any time soon. This is a conceptual problem. Or even three separate problems:

1. First of all, once you click the bold button we need to add a `<strong>` in that place and put the selection there. Why? Because we cannot reliably handle typing in that place otherwise. That `<strong>` splits the word and most browsers start to treat that as two separate words. This could be fixed either we got a mechanism for handling typing (which we won't get any time soon) or if browsers would ignore such inline elements.
2. We need to add a zero-width space in that element. Why? Because some browsers do not allow us to set the selection inside empty inline elements. ZWS helps to keep it there. Even if browsers would ignore these inline elements, ZWS is still a problem. IDK if this mechanism will be improved any time soon too, so IDK when we may get rid of it.
