### ISSUE TITLE
Add long form names in formatting dropdown menu

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/notes#528]
The __abreevs__ are cool in the label, but once expanded, we should show the full name. Take care localizing as I'm imaging the width will vary greatly. Also rename a few things, and more logically ordered the items too.

Note that `Aa` should appear when paragraphs are selected or when nothing is selected. This may be a change in behaviour, albeit just a label change.

![notes-formatting-menu](https://user-images.githubusercontent.com/68213/34784272-d04d7b7c-f5fb-11e7-97ca-331a0e42b2e0.png)

**Comment by Natim** [comment]
I did an attempt on this one, I have the following: 

![strange](https://user-images.githubusercontent.com/229453/35284431-17625492-005b-11e8-8d28-d980bf267874.png)

![full](https://user-images.githubusercontent.com/229453/35284555-6c142e20-005b-11e8-8157-13d5508289d9.png)


I wanted to do something like this, but it doesn't seems to work just yet.
```
const headingDropdown = document.querySelector('.ck-heading-dropdown > .ck-button__label');
headingDropdown.addEventListener('DOMSubtreeModified', () => {
 const value = headingDropdown.innerHTML;
 console.log(value);
 if (value == browser.i18n.getMessage('title1')) {
    headingDropdown.innerHTML = "H1";
  } else if (value == browser.i18n.getMessage('title2')) {
    headingDropdown.innerHTML = "H2";
  } else if (value == browser.i18n.getMessage('title3')) {
    headingDropdown.innerHTML = "H3";
  } else if (value == browser.i18n.getMessage('paragraph')) {
    headingDropdown.innerHTML = "P";
  }
});
```

**Comment by Natim** [comment]
@Reinmar have you got anyidea of how I can monitor the heading dropdown .ck-button__label value to change it like that?

**Comment by Reinmar** [comment]
I assume that you can't use [`config.heading.options`](https://docs.ckeditor.com/ckeditor5/latest/api/module_heading_heading-HeadingConfig.html#options) (the `title` properties there) because you want different titles in the dropdown's panel and in the button?

IMO, you should define your own dropdown. Instead of hacking the current one just define a new one which will work the way you want it. 

The code which creates the current dropdown is here:

https://github.com/ckeditor/ckeditor5-heading/blob/614987b8120d02a2035fdf37c8c5c1fdf1f4a54c/src/heading.js#L54-L115

I think that customization needs to go here: https://github.com/ckeditor/ckeditor5-heading/blob/614987b8120d02a2035fdf37c8c5c1fdf1f4a54c/src/heading.js#L92 but @jodator will need to confirm.

**Comment by Natim** [comment]
@Reinmar Are you interested that I file a pull-request to ckeditor5-heading?

**Comment by Natim** [comment]
Completely missed that we were already using https://github.com/ckeditor/ckeditor5-heading/compare/master...vladikoff:short-heading?expand=1 somehow.

**Comment by Reinmar** [comment]
The behaviour of our dropdown is different than what you want to achieve and we'd rather stay with the current solution. We even discussed recently whether this dropdown should be proposed in such a shape but we found simplifying it tricky and usually introducing UX issues. We could discuss it in a ticket in https://github.com/ckeditor/ckeditor5-heading if you have some ideas how this dropdown could be improved, but it will be easier and faster for you to just introduce your own dropdown which matches your requirements better than the default one.

BTW, one of the design decisions that we made was not to overcomplicate existing features with too many options and too much generality. Instead, we'll encourage developers to implement their  own modifications because that gives them far more flexibility and prevents us from bloating the source code (which was often a case in CKEditor 4).

**Comment by Natim** [comment]
Makes sense, thank you for your feedback.

**Comment by jodator** [comment]
@Reinmar yeah the customization is there but I saw that [Short Heading](https://github.com/ckeditor/ckeditor5-heading/compare/master...vladikoff:short-heading?expand=1) already does some customization of the dropdownModel's `label` as it should to change label of dropdown.

**Comment by ryanfeeley** [comment]
@Natim I fear my mockup was not clear. The long form name is only for the expanded part of the dropdown menu. So, for example, it would say **H1** above, and **Heading 1** below. Make sense?

**Comment by Natim** [comment]
Yes that's what I have implemented.

**Comment by Natim** [comment]
You can try this build to validate: [notes-2.2.0dev1.zip](https://github.com/mozilla/notes/files/1663169/notes-2.2.0dev1.zip)

**Comment by ryanfeeley** [comment]
@Natim  Trying now! I am expecting to see the latest design from Invision.

Quickly mocked up using the toolbox.

# Focus on normal text 
<img width="247" alt="image" src="https://user-images.githubusercontent.com/68213/35408218-4fe2c810-01dc-11e8-80c2-8233f5c299be.png">

# Focus on headings
<img width="244" alt="image" src="https://user-images.githubusercontent.com/68213/35408181-34eac440-01dc-11e8-89e6-6e74d58096b7.png">

# Focus off or in white space
<img width="251" alt="image" src="https://user-images.githubusercontent.com/68213/35408405-f3e8dc2e-01dc-11e8-9f23-de96c4f2c011.png">

@Reinmar are you saying that adding a second longform label in the dropdown introduces UX issues?

**Comment by Natim** [comment]
Ok so you Aa for Body text, goatch
