### ISSUE TITLE
Issue with Line Break on Mac OS

### ISSUE THREAD

**Issue by diogocnunes** [mozilla/notes#534]
I haven't tested this on Windows. Therefore, I will assume that the error only occurs in MacOS.

I use Firefox Notes on Mozilla Firefox 57.0.3 on MacOS 10.13.2 High Sierra. When copying a text from Text Editor or Sublime Text to Firefox Notes, line breaks are removed and the text is all on the same line ...

If I correct the text in Firefox Notes and copy it to the Text Editor or Sublime Text, in the applications the line breaks are duplicated ...

Copying and pasting between editors, the problem doesn't occur.

I suggest putting an option to configure the default line break (Unix, Mac, Windows, ...)

**Comment by diogocnunes** [comment]
Examples:

**How shows in Sublime:**

![captura de tela 2017-12-28 as 23 50 44](https://user-images.githubusercontent.com/13525900/34426009-0320ea56-ec2a-11e7-9f90-330824711fb4.png)

**How shows in Firefox Notes:**

![captura de tela 2017-12-28 as 23 50 59](https://user-images.githubusercontent.com/13525900/34426013-0b27f83e-ec2a-11e7-9ee6-49c40eb7b934.png)

**Comment by Natim** [comment]
Thank you for posting this issue, it is indeed very inconvenient.

@vladikoff I guess this is because linebreaks should be converted to <br/> on Text Plain paste?

**Comment by vladikoff** [comment]
cc @mgsy

**Comment by Mgsy** [comment]
Thanks for the information. This problem occurs not only on OS X, but also on Windows. It's caused by way how editor converts plaint text to HTML. Current conversion algorithm looks like this:
```
“a\nb” -> “a<br>b”
“a\n\nb” -> “<p>a</p><p>b</p>”
```
As we don't handle soft-line breaks, you receive the output from this issue. I've opened a discussion ticket in our CKEditor 5 repository - https://github.com/ckeditor/ckeditor5/issues/766. You can monitor it and feel free to join the discussion.
