### ISSUE TITLE
Investigate performance syncing long text

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#783]
### [Description]:

Might be able to use a WebWorker or some other cool web tech (tm)

Extracted from: https://github.com/mozilla/notes/pull/743

**Comment by sebastienbarbier** [comment]
I believe this issue was actually a mix of few issues noew fixed and should be closed.

Server was never deleting notes so syncing was way longer that it should be. Fixed in #824.
Copy/pasting was taking ages because of unoptimized behaviour in ckeditor. Fixed in #839. 

We can still improve performances using webworker on background side, but this involve important refactoring which will be done in future release. An issue has been open : #822

Based on those, I will close this issue.
