### ISSUE TITLE
Space between characters is wrongly increased depending on the sidebar width

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#854]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Linux

**[Prerequisites]:**
-Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.0.0 Beta 5) installed.
- Have at least one note in the sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
3. Adjust the width of the sidebar to different sizes.
2. Observe the space between the last characters of the title ("es!").

**[Expected result]:**
- The space between the characters in the notes title is even.

**[Actual result]:**
- The space between the last characters of the note title is wronlgy increased.

**[Notes]:**
- The issue is reproducible for different characters not only for the ones at the end of the notes title.
- Attached a screen recording of the issue:
![notes_wrongspace](https://user-images.githubusercontent.com/20083658/38137529-cda80f0c-342d-11e8-854a-5060947da93a.gif)

**Comment by sebastienbarbier** [comment]
Interesting, shouldn't this text be bold after some refactoring we did couple of weeks ago ? @ryanfeeley can you confirm ?

**Comment by sebastienbarbier** [comment]
Tried to refactor using a fix block horizontally centred instead of a full width block being resized and having text-align centred. Also a defined `letter-spacing` value do not help.
We can notice same behaviour in footer.

![letterspacingfooter](https://user-images.githubusercontent.com/3018618/38235811-9b55d36e-374c-11e8-8de7-d038a3eecc25.gif)

Any one got inspiration ? I would suggest to create a firefox bug but wanna share thoughts before.

**Comment by vladikoff** [comment]
I think this is caused by CSS transitions, but will have to check

**Comment by vladikoff** [comment]
Out of v4 for now
