### ISSUE TITLE
The Notes List is not correctly synchronized across Firefox profiles when a note is deleted

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#858]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have two Firefox profiles with the latest Notes version (4.0.0 Beta 5) enabled.
- You must be logged with the same "Firefox Notes" account on both profiles.
- Make sure you have the same notes in the "Note List" View on both profiles.

**[Steps to reproduce]:**
1. Open two browser instances with the profiles from prerequisites.
2. Focus the first browser instance and delete any note.
3. Wait until the "Synced (hour)" message is displayed in the "Notes List" View.
4. Focus the other browser instance and click the "Sync Your Notes" button from the bottom-right part of the sidebar.
5. Observe the notes in the "Notes List" View.

**[Expected result]:**
- The same notes are displayed in the "Notes List" view on both browser instances.

**[Actual result]:**
- The deleted note on the first browser instance is still displayed in the second one.

**[Notes]:**
- The issue is reproducible also on two different devices which are synced with the same Firefox Notes profile.
- Attached a screen recording of the issue:
![deleted_notes](https://user-images.githubusercontent.com/20083658/38195520-7f0f4008-3686-11e8-9c78-5fabda4f2cdf.gif)

**Comment by vladikoff** [comment]
Should be fixed in the next beta

**Comment by sebastienbarbier** [comment]
Ooooh I see, I just realised this issue occured between two different Firefox profile, which is not what I was testing 😱. Sorry, misread it. Will do some test.

**Comment by vladikoff** [comment]
Updating issue title to clarify

**Comment by sebastienbarbier** [comment]
After many investigations, seams like we do not implement kinto.js **sync process** properly.

Our sync does not send on request the `_since` parameter _(which should be automatically managed)_ so as a result we always retrieve the entire list instead of only the differences.

On delete, server create a **tombstone** which confirm it is properly handled, but those are only returned if a `_since` parameter is provided. Tombstones when received should trigger `load event` event and update properly our UI.

I could not manage to make this work, and will only be able to continue working this on next Monday. @vladikoff I guess we need to decide if this is blocking v4 release.

**Comment by vladikoff** [comment]
cc @natim

**Comment by vladikoff** [comment]
@Natim === 🚒👨‍🚒🎇

**Comment by glasserc** [comment]
Yes, based on the feedback I got when implementing chrome.storage.sync, I re-used some of the ideas here, namely that we encrypt tombstones to not leak info about what notes were deleted. (It might not have really been necessary but I had the code so I thought I would just go for it.) If we aren't sending `?_since`, that's very strange and something to investigate, but the absence of tombstones shouldn't matter because from the server perspective, the records aren't really tombstones, just more blobs of encrypted data.

**Comment by vladikoff** [comment]
>  I guess we need to decide if this is blocking v4 release.

@sebastienbarbier let's not block on it for now

**Comment by sebastienbarbier** [comment]
@glasserc we had to change the default blob deleting behavior because of multi note reaching quota too quickly. I agree would have been nice to keep it as it was, but i feld like this would have been pricy to load everything for mobile and slow bandwidth.

**Comment by glasserc** [comment]
Ah OK, that's interesting. Sorry then, I have no idea what's going on.

**Comment by vladikoff** [comment]
Couple of proposed solutions and items to keep track of:

* Keep track of LIVE notes, ignore tombstones. If there is a note that is not LIVE then delete it on sync 
* Do the "tombstone thing" and sync delete events

Scenarios to test:

"work / home sync", "mobile app sync", "upgrade from v4 to v4.1, what happens to the users when they get the fix?"

**Comment by Natim** [comment]
It is not really about keeping track of LIVE notes, it is more setting `content = encrypted('{"deleted": true}')`

**Comment by Natim** [comment]
I would be in favour of using the real tombstones too.

**Comment by vladikoff** [comment]
> I would be in favour of using the real tombstones too.
content = encrypted('{"deleted": true}')

**Comment by vladikoff** [comment]
> I would be in favour of using the real tombstones too.


content = encrypted('{"deleted": true}') 

If I understand this correctly then it sounds good :)

**Comment by Natim** [comment]
I opened sync.js I see things :( I am really worry about.

**Comment by sebastienbarbier** [comment]
I just managed to solve that issue by managing `lastModified` manually as options of sync method. 🎉.
```
collection.sync({ lastModified })
```
Will propose a PR later today.
