### ISSUE TITLE
When opening a note, set focus act weird.

### ISSUE THREAD

**Issue by sebastienbarbier** [mozilla/notes#869]
### [Description]:
When displaying a note, editor get focus but add an empty line. Also seams like not being properly aligned on ckeditor

### [Affected versions]:
Master branch (v4.0.0-beta.6) on Mac OS

### [Steps to reproduce]:
Open a note.

### [Expected result]:
Get focus

### [Actual result]:
Get focus but add empty line

### [Additional Notes]:
![setfocus](https://user-images.githubusercontent.com/3018618/38254874-8b6a72c4-3784-11e8-8c72-a3a66f128c75.gif)

Spoiler alert: I will provide a fix in a minute 😉

**Comment by Softvision-MariusComan** [comment]
I was investigating the same issue and I've found out that this behavior is reproducible only on the Release channel. Considering this using the Mozregression tool I've found a regression window:

First good revision: 575562183a3bc245c50dcf45d8dc21043b4565ae
Last bad revision: 490f87831c110acaa3eb966679ad94a1eaf51dd9
Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=490f87831c110acaa3eb966679ad94a1eaf51dd9&tochange=575562183a3bc245c50dcf45d8dc21043b4565ae

From the pushlog it seems that Bug 662591 has fixed this behavior.

Additional Notes:

- The "Space" and the "Enter" keys are not working on the newly created row.
- The text caret is also placed at the beginning of the new row.
- If a new note is created only the formatting options are grayed out.
- The issue is not reproducible with the latest Beta and Nightly builds.
- The issue is no longer reproducible if you click inside the sidebar's content area.
- Attached a screen recording of the issue:
